models/followship.js, models/index.js, models/like.js, models/reply.js, models/tweet.js, models/user.js
=> feat: model initialize

migrations/20190115071418-create-followship.js, migrations/20190115071419-create-like.js, migrations/20190115071420-create-reply.js, migrations/20190115071420-create-tweet.js, migrations/20190115071421-create-user.js, models/like.js, models/reply.js, models/tweet.js, models/user.js
更改了model 的一些typo，跟修正migration檔
=> feat: modify migration and fix model typo

app.js, config/passport.js, controllers/tweet-controller.js, controllers/user-controller.js, helpers/auth-helpers.js, routes/apis/index.js
1.修改如果用錯誤的帳號密碼login 程式會崩潰的問題 （修改passport）
2.新增getTweet function
=> Tweet functions

config/passport.js, controllers/admin-controller.js, controllers/user-controller.js, routes/apis/modules/admin.js
=> feat: add admin login function

controllers/tweet-controller.js, helpers/combination-helpers.js, routes/apis/index.js, seeders/20221215074120-likes-seed-file.js, seeders/20221215082349-followships-seed-file.js
新增getTweet功能，另外也有新增Like Model 、 Followship Model 的簡易種子資料
=> getTweet function 

controllers/tweet-controller.js, routes/apis/index.js
新增 like/unlike 特定tweet的功能
對應的路由分別為：
POST api/tweets/:id/unlike
POST api/tweets/:id/like
=> feat: add add/remove like function

controllers/user-controller.js, routes/apis/index.js
=> feat: getUserTweets function

controllers/admin-controller.js, controllers/user-controller.js, routes/apis/index.js, routes/apis/modules/admin.js
新增 /api/admin/get/users 路由
修正後台admin路由的middleware位置，現在後台使用者可以正常登入驗證
=> add admin getUser function

app.js, controllers/admin-controller.js, package-lock.json, routes/apis/modules/admin.js
新增 DELETE /api/admin/tweets/:id 路由
admin 帳號可在後台刪除tweet
=> feat: add admin deleteTweet function

controllers/tweet-controller.js, routes/apis/index.js, routes/apis/modules/admin.js
新增 POST /api/tweets/:tweet_id/replies 路由
user 帳號可在前台頁面對任何一條tweet新增reply
=> feat: add replyTweet function

controllers/tweet-controller.js, routes/apis/index.js
新增 GET /api/tweets/:tweet_id/replies 路由
user 帳號可取得任何一條tweet的所有replies
=> feat: add getReplies function

controllers/tweet-controller.js, controllers/user-controller.js, models/like.js, models/reply.js, models/tweet.js, models/user.js, routes/apis/index.js, seeders/20221213053543-tweets-seed-file.js, seeders/20221213075653-replies-seed-file.js, seeders/20221215074120-likes-seed-file.js
新增 GET /api/users/:id/replied_tweets 路由
user 帳號可在前台頁面看任一使用者頁面時，看到該使用者回覆過的所有內容
另外有對Model的外鍵部分做修正，把專案內所有用到UserId(User_id) 、TwitterId(Twitter_id)的程式碼字首都改大寫以符合專案規格。
=> feat: add getRepliedTweets function and modify some typo

controllers/tweet-controller.js, controllers/user-controller.js, routes/apis/index.js
新增 POST /api/tweets/:tweet_id/likes 路由
user 帳號可在前台頁面看任一使用者頁面時，看到該使用者like過的所有推文
=> feat: add getUserLikes function

controllers/tweet-controller.js, routes/apis/index.js
新增 GET /api/tweets/following 路由
user 帳號可在首頁看見目前追蹤中使用者所有的推文
=> add getTweetsFollowing function

controllers/admin-controller.js, controllers/tweet-controller.js, controllers/user-controller.js
=> feat: debug and modify apis

controllers/user-controller.js, routes/apis/index.js
=> feat: getUserFollowing function completed

controllers/user-controller.js, package-lock.json, routes/apis/index.js
=> feat: getRecommendUsers function completed

controllers/user-controller.js
使用者修改account與email時，新增判斷不能與其他使用者相同。
=> feat: avoid change the same account or email with other users.

README.md, controllers/user-controller.js
=> Add readme file

controllers/user-controller.js
=> feat: block self from getRecommendUsers list

controllers/tweet-controller.js
修正 GET /api//tweets/following 路由
現在使用者在首頁看推特清單時，也會看到自己的全部推文
=> modify get tweet following function

controllers/user-controller.js
=> feat: change user default avatar and background

middleware/api-auth.js, routes/apis/index.js
新增 GET /api/TokenAuthenticate 路由
這個路由是用來驗證使用者目前登入狀態
=> feat: add TokenAuthenticate middleware

controllers/tweet-controller.js
修改 GET /api/tweets/following 路由
現在會在回傳的物件中加上isLike的屬性
=> feat: modify get tweet following function

config/passport.js, controllers/tweet-controller.js, controllers/user-controller.js
修正 getUserTweets  跟  getTweetFollowing 功能無法正確顯示，使用者對 tweet 是否為 like的狀態
=> modify getUserTweets and getTweetFollowing function

controllers/admin-controller.js
修正GET /api/admin/users 路由
現在取得的全部使用者清單會排除掉管理者自身的帳號
=> modify getAdminUsers function

controllers/tweet-controller.js
修改 GET /api/tweets/:tweet_id路由
現在會在回傳的物件中加上isLike的屬性
=> feat: modify getTweet function

controllers/user-controller.js
修正 GET /api/users/getRecommendUsers 路由
排除回傳的資料會包含管理者帳號的問題
=> modify getRecommendUser function

controllers/admin-controller.js, controllers/user-controller.js
修改  getUserTweets 跟 getUserLikes 功能
修正回傳的物件中replyAmount變數名稱錯誤問題
=> feat: modify getUserTweets and getUserLikes function

controllers/tweet-controller.js, controllers/user-controller.js
=> modify error messages

controllers/tweet-controller.js
=> feat: modify getTweets function

controllers/tweet-controller.js, controllers/user-controller.js
=> feat: modify getUserLikes function

controllers/user-controller.js
=> feat: modify error message

controllers/user-controller.js, routes/apis/index.js
新增 GET /api/users/self 路由 及getUserSelf function
此路由可取得登入的使用者的個人資料
=>  feat: add getUserSelf function
